In [6]:
import numpy as np
array=np.array([[1,2,3],[2,3,4]])

print(array)

print("Number of dim:",array.ndim)

print("shape:",array.shape)

print("size",array.size)


[[1 2 3]
 [2 3 4]]
Number of dim: 2
shape: (2, 3)
size 6


In [7]:
array=np.array([2,23,4])
print(array)

[ 2 23  4]


In [11]:
array=np.array([2,23,4],dtype=np.int64)
print(array.dtype)

array=np.array([2,23,4],dtype=np.int32)
print(array.dtype)

array=np.array([2,23,4],dtype=np.int)
print(array.dtype)

array=np.array([2,23,4],dtype=np.float32)
print(array.dtype)

array=np.array([2,23,4],dtype=np.float)
print(array.dtype)

int64
int32
int32
float32
float64


In [12]:

array=np.array([[2,23,4],[1,2,3]])
print(array)


[[ 2 23  4]
 [ 1  2  3]]


In [14]:

array=np.zeros((3,4))
print(array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
array=np.ones((3,4))
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
array1=np.empty((3,4),dtype=float)
print(array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [25]:
a=np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
a=np.linspace(1,10,6)
print(a)

a=np.linspace(1,10,6).reshape((2,3))
print(a)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [41]:
a=np.array([10,20,30,40])
b=np.arange(4)

print(a)
print(b)

c_dot=np.dot(a,b)

print(a==20)

#c=a*b
print(c)

[10 20 30 40]
[0 1 2 3]
[False  True False False]
[  0  20  60 120]
